# Generated by Django 2.0.7 on 2018-08-15 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('blockchain_name', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['blockchain_name'],
            },
        ),
        migrations.CreateModel(
            name='CapUnit',
            fields=[
                ('unit', models.CharField(max_length=6, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['unit'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['country_name'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('symbol', models.CharField(max_length=3, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='ICO',
            fields=[
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('last_user', models.CharField(blank=True, default='', max_length=50)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ICOInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_sale_date', models.DateField(blank=True, help_text='The date when ICO tokens first start to sell.', null=True)),
                ('last_sale_date', models.DateField(blank=True, help_text='The last date when ICO tokens will be sold.', null=True)),
                ('available_tokens', models.PositiveIntegerField(help_text='The number of tokens available for sale to the public.')),
                ('total_tokens', models.PositiveIntegerField(help_text='The total number of tokens in this ICO')),
                ('hard_cap', models.PositiveIntegerField(help_text='The maximum number of tokens to be sold for this ICO.')),
                ('soft_cap', models.PositiveIntegerField(help_text='The minimum number of tokens to be sold if ICO will go ahead.')),
                ('core_investors', models.DecimalField(decimal_places=2, help_text='something informative.', max_digits=3)),
                ('working_capital', models.DecimalField(decimal_places=2, help_text='something informative.', max_digits=3)),
                ('cost_of_sales', models.DecimalField(decimal_places=2, help_text='something informative.', max_digits=3)),
                ('externals', models.DecimalField(decimal_places=2, help_text='something informative.', max_digits=3)),
                ('public', models.DecimalField(decimal_places=2, help_text='something informative.', max_digits=3)),
                ('number_of_rounds', models.PositiveIntegerField(help_text='The number of rounds in the ICO Token Sale.')),
                ('highest_mentioned_price', models.DecimalField(decimal_places=2, help_text='Highest price a token sold for during ICO.', max_digits=5)),
                ('lowest_mentioned_price', models.DecimalField(decimal_places=2, help_text='Lowest price a token sold for during ICO.', max_digits=5)),
                ('comments', models.TextField(blank=True, default='', help_text='Report any anomalies and/or ask questions.', max_length=250)),
                ('last_user', models.CharField(blank=True, default='', max_length=50)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('blockchain_name', models.ManyToManyField(help_text='Select a Blockchain for this ICO', to='manageicodata.Blockchain')),
                ('cap_unit', models.ManyToManyField(help_text='Select a CapUnit for this ICO', to='manageicodata.CapUnit')),
                ('country', models.OneToOneField(help_text='Select a Country for this ICO', on_delete=django.db.models.deletion.CASCADE, to='manageicodata.Country')),
                ('ico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manageicodata.ICO')),
                ('price_currency', models.ManyToManyField(help_text='The currency used to buy this ICOs tokens.', to='manageicodata.Currency')),
            ],
            options={
                'ordering': ['ico'],
            },
        ),
    ]
