# Generated by Django 2.0.7 on 2018-08-11 01:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CapUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=6)),
            ],
            options={
                'ordering': ['unit'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=3)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='ICO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('blockchain', models.ManyToManyField(help_text='Select a Blockchain for this ICO', to='manageicodata.Blockchain')),
            ],
        ),
        migrations.CreateModel(
            name='ICOInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular ICO', primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=30)),
                ('start_sale_date', models.DateField(blank=True, null=True)),
                ('last_sale_date', models.DateField(blank=True, null=True)),
                ('available_tokens', models.PositiveIntegerField()),
                ('total_tokens', models.PositiveIntegerField()),
                ('hard_cap', models.PositiveIntegerField()),
                ('soft_cap', models.PositiveIntegerField()),
                ('core_investors', models.DecimalField(decimal_places=2, max_digits=3)),
                ('working_capital', models.DecimalField(decimal_places=2, max_digits=3)),
                ('cost_of_sales', models.DecimalField(decimal_places=2, max_digits=3)),
                ('externals', models.DecimalField(decimal_places=2, max_digits=3)),
                ('public', models.DecimalField(decimal_places=2, max_digits=3)),
                ('number_of_rounds', models.PositiveIntegerField()),
                ('highest_mentioned_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lowest_mentioned_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cap_unit', models.ManyToManyField(help_text='Select a CapUnit for this ICO', to='manageicodata.CapUnit')),
                ('ico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manageicodata.ICO')),
                ('price_currency', models.ManyToManyField(help_text='Select a Currency for this ICO', to='manageicodata.Currency')),
            ],
            options={
                'ordering': ['ico'],
            },
        ),
    ]
