# Generated by Django 2.0.7 on 2018-08-14 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageicodata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['country_name'],
            },
        ),
        migrations.AddField(
            model_name='icoinstance',
            name='comments',
            field=models.TextField(blank=True, default='', help_text='Report any anomalies and/or ask questions.', max_length=250),
        ),
        migrations.AddField(
            model_name='icoinstance',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='icoinstance',
            name='last_user',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='icoinstance',
            name='available_tokens',
            field=models.PositiveIntegerField(help_text='The number of tokens available for sale to the public.'),
        ),
        migrations.AlterField(
            model_name='icoinstance',
            name='core_investors',
            field=models.DecimalField(decimal_places=2, help_text='something informative.', max_digits=3),
        ),
        migrations.AlterField(
            model_name='icoinstance',
            name='cost_of_sales',
            field=models.DecimalField(decimal_places=2, help_text='something informative.', max_digits=3),
        ),
        migrations.AlterField(
            model_name='icoinstance',
            name='country',
            field=models.OneToOneField(help_text='Select a Country for this ICO', on_delete=django.db.models.deletion.CASCADE, to='manageicodata.Country'),
        ),
        migrations.AlterField(
            model_name='icoinstance',
            name='externals',
            field=models.DecimalField(decimal_places=2, help_text='something informative.', max_digits=3),
        ),
        migrations.AlterField(
            model_name='icoinstance',
            name='hard_cap',
            field=models.PositiveIntegerField(help_text='The maximum number of tokens to be sold for this ICO.'),
        ),
        migrations.AlterField(
            model_name='icoinstance',
            name='highest_mentioned_price',
            field=models.DecimalField(decimal_places=2, help_text='Highest price a token sold for during ICO.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='icoinstance',
            name='last_sale_date',
            field=models.DateField(blank=True, help_text='The last date when ICO tokens will be sold.', null=True),
        ),
        migrations.AlterField(
            model_name='icoinstance',
            name='lowest_mentioned_price',
            field=models.DecimalField(decimal_places=2, help_text='Lowest price a token sold for during ICO.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='icoinstance',
            name='number_of_rounds',
            field=models.PositiveIntegerField(help_text='The number of rounds in the ICO Token Sale.'),
        ),
        migrations.AlterField(
            model_name='icoinstance',
            name='price_currency',
            field=models.ManyToManyField(help_text='The currency used to buy this ICOs tokens.', to='manageicodata.Currency'),
        ),
        migrations.AlterField(
            model_name='icoinstance',
            name='public',
            field=models.DecimalField(decimal_places=2, help_text='something informative.', max_digits=3),
        ),
        migrations.AlterField(
            model_name='icoinstance',
            name='soft_cap',
            field=models.PositiveIntegerField(help_text='The minimum number of tokens to be sold if ICO will go ahead.'),
        ),
        migrations.AlterField(
            model_name='icoinstance',
            name='start_sale_date',
            field=models.DateField(blank=True, help_text='The date when ICO tokens first start to sell.', null=True),
        ),
        migrations.AlterField(
            model_name='icoinstance',
            name='total_tokens',
            field=models.PositiveIntegerField(help_text='The total number of tokens in this ICO'),
        ),
        migrations.AlterField(
            model_name='icoinstance',
            name='working_capital',
            field=models.DecimalField(decimal_places=2, help_text='something informative.', max_digits=3),
        ),
    ]
