# Generated by Django 2.0.7 on 2018-08-15 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageicodata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icoinstance',
            name='country',
        ),
        migrations.AddField(
            model_name='country',
            name='icoinstance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manageicodata.ICOInstance'),
        ),
    ]
