# Generated by Django 2.0.7 on 2018-08-18 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageicodata', '0003_auto_20180815_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icoinstance',
            name='country',
            field=models.ForeignKey(help_text='Select a Country for this ICO', null=True, on_delete=django.db.models.deletion.SET_NULL, to='manageicodata.Country'),
        ),
    ]
