# Generated by Django 2.0.7 on 2018-08-18 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageicodata', '0002_auto_20180814_0859'),
        ('manageicodata', '0004_auto_20180818_0258'),
    ]

    operations = [
    ]
