# Generated by Django 2.0.7 on 2018-08-20 07:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manageicodata', '0004_auto_20180818_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icoinstance',
            name='cap_unit',
        ),
        migrations.AddField(
            model_name='icoinstance',
            name='hard_cap_unit',
            field=models.ManyToManyField(help_text='Select a CapUnit for this ICO', related_name='icoinstance_hardcap', to='manageicodata.CapUnit'),
        ),
        migrations.AddField(
            model_name='icoinstance',
            name='soft_cap_unit',
            field=models.ManyToManyField(help_text='Select a CapUnit for this ICO', related_name='icoinstance_softcap', to='manageicodata.CapUnit'),
        ),
        migrations.AddField(
            model_name='icoinstance',
            name='total_tokens_not_mentioned',
            field=models.BooleanField(default=False, help_text='Check if Total Tokens not mentioned.'),
        ),
        migrations.AddField(
            model_name='icoinstance',
            name='total_tokens_unlimited',
            field=models.BooleanField(default=False, help_text='Check if Total Tokens are unlimited.'),
        ),
        migrations.AlterField(
            model_name='ico',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ico',
            name='symbol',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='icoinstance',
            name='ico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manageicodata.ICO'),
        ),
        migrations.AlterUniqueTogether(
            name='ico',
            unique_together={('symbol', 'name')},
        ),
    ]
