# Generated by Django 2.0.7 on 2018-08-20 07:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manageicodata', '0006_auto_20180820_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='ico',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
